CREATE TABLE wp_competidores (
    id serial PRIMARY KEY,
    name VARCHAR(255) not null,
    descricao text not null,
    points int not null
);

INSERT INTO wp_competidores (id, name, descricao, points) VALUES
(1, 'Enrico Elias Ruan da Silva', 'Enrico Elias Ruan da Silva, nascido em 03/02/1986 na cidade de Tucuruí-PA. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2004', 15),
(2, 'Elias Caio Enrico Castro', 'Elias Caio Enrico Castro, nascido em 16/02/1997 na cidade de Brasília-DF. \r\nTem como prêmio mais memorável o terceiro lugar no Nacional de Tênis de Mesa de 2002', 35),
(3, 'Larissa Alessandra da Rocha', 'Larissa Alessandra da Rocha, nascido em 03/04/1947 na cidade de Boa Vista-RR. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2000', 92),
(4, 'Fernanda Simone Sônia Almeida', 'Fernanda Simone Sônia Almeida, nascido em 16/05/1966 na cidade de Duque de Caxias-RJ. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2011', 33),
(5, 'Marina Marlene Carla Fogaça', 'Marina Marlene Carla Fogaça, nascido em 06/06/1945 na cidade de Natal-RN. \r\nTem como prêmio mais memorável o terceiro lugar no Nacional de Tênis de Mesa de 2006', 38),
(6, 'João Erick Ferreira', 'João Erick Ferreira, nascido em 06/06/1998 na cidade de Fortaleza-CE. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2000', 18),
(7, 'Milena Tereza Esther da Costa', 'Milena Tereza Esther da Costa, nascido em 10/02/1954 na cidade de Ariquemes-RO. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2021', 68),
(8, 'Pietro Victor Diego Fogaça', 'Pietro Victor Diego Fogaça, nascido em 03/04/1981 na cidade de João Pessoa-PB. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2000', 7),
(9, 'Larissa Bárbara Vieira', 'Larissa Bárbara Vieira, nascido em 27/04/1997 na cidade de Boa Vista-RR. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2008', 11),
(10, 'Renata Aurora das Neves', 'Renata Aurora das Neves, nascido em 10/04/1994 na cidade de Iguatu-CE. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2007', 1),
(11, 'Juan Manuel Assis', 'Juan Manuel Assis, nascido em 10/07/1978 na cidade de São Luís-MA. \r\nTem como prêmio mais memorável o segundo lugar no Mundial de Tênis de Mesa de 2018', 69),
(12, 'Miguel Martin Barbosa', 'Miguel Martin Barbosa, nascido em 25/05/1958 na cidade de São Luís-MA. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2010', 57),
(13, 'Emily Lavínia Rafaela Cavalcanti', 'Emily Lavínia Rafaela Cavalcanti, nascido em 12/04/1948 na cidade de Mossoró-RN. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2007', 77),
(14, 'César Luan Juan Moraes', 'César Luan Juan Moraes, nascido em 03/07/1994 na cidade de Goiânia-GO. \r\nTem como prêmio mais memorável o terceiro lugar no Mundial de Tênis de Mesa de 2003', 55),
(15, 'Nicole Patrícia Souza', 'Nicole Patrícia Souza, nascido em 26/04/1977 na cidade de Rio de Janeiro-RJ. \r\nTem como prêmio mais memorável o terceiro lugar no Nacional de Tênis de Mesa de 2008', 42),
(16, 'Betina Stella Fogaça', 'Betina Stella Fogaça, nascido em 17/02/1947 na cidade de Serra-ES. \r\nTem como prêmio mais memorável o terceiro lugar no Nacional de Tênis de Mesa de 2012', 10),
(17, 'Diogo Theo das Neves', 'Diogo Theo das Neves, nascido em 19/04/1953 na cidade de Recife-PE. \r\nTem como prêmio mais memorável o terceiro lugar no Mundial de Tênis de Mesa de 2008', 55),
(18, 'Tereza Eloá Rafaela Melo', 'Tereza Eloá Rafaela Melo, nascido em 05/02/1978 na cidade de Araguaína-TO. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2005', 20),
(19, 'Sebastião Joaquim Carvalho', 'Sebastião Joaquim Carvalho, nascido em 20/03/1968 na cidade de São Paulo-SP. \r\nTem como prêmio mais memorável o segundo lugar no Mundial de Tênis de Mesa de 2007', 87),
(20, 'Benedito Márcio Lorenzo Lima', 'Benedito Márcio Lorenzo Lima, nascido em 25/02/1969 na cidade de Natal-RN. \r\nTem como prêmio mais memorável o segundo lugar no Mundial de Tênis de Mesa de 2012', 79),
(21, 'Emilly Mariah Ramos', 'Emilly Mariah Ramos, nascido em 07/05/1984 na cidade de Ji-Paraná-RO. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2003', 67),
(22, 'Brenda Louise Cavalcanti', 'Brenda Louise Cavalcanti, nascido em 01/03/1974 na cidade de Itabuna-BA. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2005', 19),
(23, 'Nicolas Bento Fogaça', 'Nicolas Bento Fogaça, nascido em 10/07/1954 na cidade de Teresina-PI. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2005', 37),
(24, 'Nicolas Gabriel Figueiredo', 'Nicolas Gabriel Figueiredo, nascido em 08/01/1970 na cidade de Brasília-DF. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2012', 19),
(25, 'Igor Levi Viana', 'Igor Levi Viana, nascido em 07/07/1945 na cidade de Rio Branco-AC. \r\nTem como prêmio mais memorável o terceiro lugar no Mundial de Tênis de Mesa de 2000', 91),
(26, 'Maitê Fátima Rodrigues', 'Maitê Fátima Rodrigues, nascido em 03/04/1964 na cidade de Brasília-DF. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2004', 41),
(27, 'Andreia Márcia Simone da Paz', 'Andreia Márcia Simone da Paz, nascido em 08/06/1978 na cidade de Marabá-PA. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2015', 49),
(28, 'Yasmin Renata da Costa', 'Yasmin Renata da Costa, nascido em 26/02/1963 na cidade de Brasília-DF. \r\nTem como prêmio mais memorável o terceiro lugar no Mundial de Tênis de Mesa de 2010', 15),
(29, 'Lívia Agatha Barros', 'Lívia Agatha Barros, nascido em 23/02/1968 na cidade de Jacareí-SP. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2000', 42),
(30, 'Arthur Luiz Souza', 'Arthur Luiz Souza, nascido em 12/05/1954 na cidade de Marabá-PA. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2001', 16),
(31, 'Rosa Fabiana Ester Farias', 'Rosa Fabiana Ester Farias, nascido em 27/02/1944 na cidade de Brusque-SC. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2020', 74),
(32, 'Isabel Luzia Vitória Viana', 'Isabel Luzia Vitória Viana, nascido em 16/01/1965 na cidade de Fortaleza-CE. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2020', 90),
(33, 'Vitor Marcos Alexandre da Conceição', 'Vitor Marcos Alexandre da Conceição, nascido em 24/02/1947 na cidade de Juazeiro do Norte-CE. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2001', 99),
(34, 'Maya Marcela Drumond', 'Maya Marcela Drumond, nascido em 05/06/1964 na cidade de Luziânia-GO. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2014', 74),
(35, 'Lorena Heloise Sophia Monteiro', 'Lorena Heloise Sophia Monteiro, nascido em 08/05/1951 na cidade de Aracaju-SE. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2014', 53),
(36, 'Andrea Luana Juliana Pinto', 'Andrea Luana Juliana Pinto, nascido em 09/03/1992 na cidade de Vila Velha-ES. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2009', 74),
(37, 'Murilo Elias Araújo', 'Murilo Elias Araújo, nascido em 21/04/1999 na cidade de Parnamirim-RN. \r\nTem como prêmio mais memorável o primeiro lugar no Nacional de Tênis de Mesa de 2013', 27),
(38, 'Erick Mário Sales', 'Erick Mário Sales, nascido em 22/02/1990 na cidade de Brasília-DF. \r\nTem como prêmio mais memorável o primeiro lugar no Estadual de Tênis de Mesa de 2019', 82),
(39, 'Miguel Giovanni de Paula', 'Miguel Giovanni de Paula, nascido em 12/06/1961 na cidade de Cariacica-ES. \r\nTem como prêmio mais memorável o primeiro lugar no Estadual de Tênis de Mesa de 2015', 94),
(40, 'Vera Aurora Emily Jesus', 'Vera Aurora Emily Jesus, nascido em 23/04/1947 na cidade de Natal-RN. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2013', 39),
(41, 'Agatha Elza Corte Real', 'Agatha Elza Corte Real, nascido em 22/05/1964 na cidade de Parnamirim-RN. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2017', 8),
(42, 'Mirella Cecília Caroline Nunes', 'Mirella Cecília Caroline Nunes, nascido em 27/04/1997 na cidade de Cuiabá-MT. \r\nTem como prêmio mais memorável o terceiro lugar no Mundial de Tênis de Mesa de 2006', 71),
(43, 'Carlos Manoel Assis', 'Carlos Manoel Assis, nascido em 09/02/1983 na cidade de Campinas-SP. \r\nTem como prêmio mais memorável o primeiro lugar no Estadual de Tênis de Mesa de 2010', 35),
(44, 'Patrícia Stefany Daniela Lopes', 'Patrícia Stefany Daniela Lopes, nascido em 14/06/1980 na cidade de Gravataí-RS. \r\nTem como prêmio mais memorável o segundo lugar no Estadual de Tênis de Mesa de 2015', 87),
(45, 'Rafaela Rosângela Ester Duarte', 'Rafaela Rosângela Ester Duarte, nascido em 24/02/1961 na cidade de Santa Rita-PB. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2013', 30),
(46, 'Sônia Alice Mariah Moura', 'Sônia Alice Mariah Moura, nascido em 24/03/1990 na cidade de Aparecida de Goiânia-GO. \r\nTem como prêmio mais memorável o segundo lugar no Nacional de Tênis de Mesa de 2013', 56),
(47, 'Vanessa Aline Antonella Ferreira', 'Vanessa Aline Antonella Ferreira, nascido em 26/03/2000 na cidade de Porto Velho-RO. \r\nTem como prêmio mais memorável o segundo lugar no Mundial de Tênis de Mesa de 2019', 2),
(48, 'Rafaela Jaqueline Ramos', 'Rafaela Jaqueline Ramos, nascido em 16/02/1945 na cidade de Itabuna-BA. \r\nTem como prêmio mais memorável o terceiro lugar no Estadual de Tênis de Mesa de 2019', 54),
(49, 'Mateus Lucca Raimundo da Luz', 'Mateus Lucca Raimundo da Luz, nascido em 12/07/1986 na cidade de Colatina-ES. \r\nTem como prêmio mais memorável o terceiro lugar no Nacional de Tênis de Mesa de 2000', 54),
(50, 'Bárbara Patrícia Yasmin Melo', 'Bárbara Patrícia Yasmin Melo, nascido em 14/04/1996 na cidade de Teresina-PI. \r\nTem como prêmio mais memorável o primeiro lugar no Mundial de Tênis de Mesa de 2000', 2);